/*
   Generated by EX4-TO-MQ4 decompiler V4.0.427.4 [-]
   Website: https://purebeam.biz
   E-mail : purebeam@gmail.com
*/
#property copyright "Copyright © 2012, Dean Malone"
#property link      "http://www.synergyprotrader.com"

#property indicator_chart_window

#import "CompassFX.dll"
   string gGrab(string a0, string a1);
#import "synergy_pro.dll"
   string returnReg(string a0, string a1);
#import

int g_file_76;
bool gi_80 = FALSE;
string gs_unused_84;
double gd_unused_92 = 1.1;
extern string Custom_Indicator = "Synergy Pro MTF";
extern string Copyright = "© 2012, Dean Malone";
extern string Web_Address = "www.synergyprotrader.com";
extern string Corner = "=== Corner settings ===";
extern string Corner_Selection_1 = "0 = Upper left   1 = Upper right";
extern string Corner_Selection_2 = "2 = Lower left   3 = Lower right";
extern int MTF_Corner = 2;
extern string Color = "=== Color settings ===";
extern color Text_Color = SlateGray;
extern color Arrow_Up_Color = LimeGreen;
extern color Arrow_Down_Color = Red;
extern color Arrow_Caution_Color = Yellow;
extern color APB_Up_Color = DodgerBlue;
extern color APB_Down_Color = Red;
bool gi_unused_184 = TRUE;
string gs_192 = "Synergy_Pro_APB_Arrows";
string gs_200 = "987987987eee98797";
string gs_208 = "Synergy_Pro_APB";
int gia_216[] = {5, 15, 30, 60, 240, 1440, 10080};
string gsa_220[] = {"M5", "M15", "M30", "H1", "H4", "D1", "W1"};
string gsa_224[];
int gi_228 = 7;
int gia_232[7][2];
bool gi_unused_248 = FALSE;

int f0_2() {
   int str2int_0;
   bool li_4;
   int li_8;
   g_file_76 = FileOpen("synergy_d.bin", FILE_CSV|FILE_READ);
   if (g_file_76 < 1) li_4 = FALSE;
   else {
      str2int_0 = StrToInteger(FileReadString(g_file_76));
      FileClose(g_file_76);
      li_4 = TRUE;
   }
   if (TimeLocal() - str2int_0 >= 86400 || li_4 == FALSE) {
      li_8 = f0_1();
      switch (li_8) {
      case 0:
         g_file_76 = FileOpen("synergy_d.bin", FILE_WRITE, 8);
         if (g_file_76 < 1) {
            Print("Cannot open password cache!");
            return (0);
         }
         FileWrite(g_file_76, TimeLocal());
         FileClose(g_file_76);
         break;
      case 1:
         Alert("Invalid software key provided!! Please re-install the software with the correct key.");
         gi_80 = TRUE;
         break;
      case 4:
         Alert("Your account has been disabled! Please contact support@compassfx.com");
         gi_80 = TRUE;
         break;
      case 5:
         Alert("Server error!! Please make sure you are connected to the Internet and try again.");
         gi_80 = TRUE;
         break;
      case 6:
         Alert("No key found in your registry (could be a bad installation)! Please re-install Synergy.");
         gi_80 = TRUE;
      }
   }
   return (0);
}

int f0_1() {
   string ls_unused_0;
   string ls_unused_8;
   string ls_unused_16;
   string ls_24 = returnReg("Software\\CompassFX\\Synergy", "key");
   if (ls_24 == "") return (6);
   string ls_32 = "key=" + ls_24;
   string ls_40 = gGrab("http://www.compassfx.com/synergy_scripts/s_login.php", ls_32);
   Print("Result -- ", ls_40);
   if (StringSubstr(ls_40, 0, 1) == "0") {
      gs_unused_84 = ls_40;
      return (0);
   }
   if (StringSubstr(ls_40, 0, 1) == "1") return (1);
   if (StringSubstr(ls_40, 0, 1) == "4") return (4);
   return (5);
}

int init() {
   string str_concat_0;
   int lia_12[];
   string lsa_16[];
   int li_20;
   HideTestIndicators(TRUE);
   ArrayResize(gsa_224, gi_228);
   if (MTF_Corner == 1 || MTF_Corner == 3) {
      ArrayCopy(lia_12, gia_216);
      ArrayCopy(lsa_16, gsa_220);
      li_20 = gi_228 - 1;
      for (int index_8 = 0; index_8 < gi_228; index_8++) {
         gia_216[index_8] = lia_12[li_20];
         gsa_220[index_8] = lsa_16[li_20];
         li_20--;
      }
   }
   for (index_8 = 0; index_8 < gi_228; index_8++) gsa_224[index_8] = StringConcatenate("SynProMTF_", gsa_220[index_8]);
   int li_24 = 120;
   string ls_28 = "a";
   ls_28 = StringSetChar(ls_28, 0, li_24);
   for (int index_52 = 0; index_52 < gi_228; index_52++) {
      gia_232[index_52][0] = 22 * index_52 + 5;
      if (MTF_Corner == 0) gia_232[index_52][1] = 17;
      else gia_232[index_52][1] = 5;
      str_concat_0 = StringConcatenate(gsa_224[index_52], "Status");
      ObjectCreate(str_concat_0, OBJ_LABEL, 0, 0, 0, 0, 0);
      ObjectSet(str_concat_0, OBJPROP_CORNER, MTF_Corner);
      ObjectSet(str_concat_0, OBJPROP_XDISTANCE, gia_232[index_52][0]);
      ObjectSet(str_concat_0, OBJPROP_YDISTANCE, gia_232[index_52][1] + 12);
      ObjectSetText(str_concat_0, CharToStr(110), 12, "WingDings", White);
      str_concat_0 = StringConcatenate(gsa_224[index_52], "Lab");
      ObjectCreate(str_concat_0, OBJ_LABEL, 0, 0, 0, 0, 0);
      ObjectSet(str_concat_0, OBJPROP_CORNER, MTF_Corner);
      ObjectSet(str_concat_0, OBJPROP_XDISTANCE, gia_232[index_52][0]);
      ObjectSet(str_concat_0, OBJPROP_YDISTANCE, gia_232[index_52][1]);
      ObjectSetText(str_concat_0, gsa_220[index_52], 8, "Tahoma", Text_Color);
   }
   IndicatorShortName("Synergy_Pro_MTF");
   //f0_2();
   return (0);
}

int deinit() {
   f0_3();
   ObjectDelete("SynProMTF_D1Lab");
   return (0);
}

int start() {
   string str_concat_40;
   if (gi_80) return (0);
   for (int count_16 = 0; count_16 < gi_228; count_16++) f0_0(count_16);
   int li_32 = 0;
   int li_36 = 0;
   int li_20 = 0;
   int li_24 = 0;
   for (int index_28 = 0; index_28 < gi_228; index_28++) {
      str_concat_40 = StringConcatenate(gsa_224[index_28], "Status");
      li_20 = ObjectGet(str_concat_40, OBJPROP_XDISTANCE);
      if (li_20 != gia_232[index_28][0]) li_32 = li_20 - gia_232[index_28][0];
      li_24 = ObjectGet(str_concat_40, OBJPROP_YDISTANCE);
      if (li_24 != gia_232[index_28][1]) li_36 = li_24 - gia_232[index_28][1];
      if (li_32 != 0 || li_36 != 0) break;
   }
   if (li_32 != 0 || li_36 != 0) {
      for (index_28 = 0; index_28 < gi_228; index_28++) {
         str_concat_40 = StringConcatenate(gsa_224[index_28], "Status");
         gia_232[index_28][0] += li_32;
         gia_232[index_28][1] += li_36;
         ObjectSet(str_concat_40, OBJPROP_XDISTANCE, gia_232[index_28][0]);
         ObjectSet(str_concat_40, OBJPROP_YDISTANCE, gia_232[index_28][1]);
         str_concat_40 = StringConcatenate(gsa_224[index_28], "Lab");
         ObjectSet(str_concat_40, OBJPROP_XDISTANCE, gia_232[index_28][0]);
         ObjectSet(str_concat_40, OBJPROP_YDISTANCE, gia_232[index_28][1] - 12);
      }
   }
   return (0);
}

void f0_0(int ai_0) {
   int fontsize_4 = 12;
   string str_concat_8 = StringConcatenate(gsa_224[ai_0], "Status");
   if (iCustom(NULL, gia_216[ai_0], gs_192, "", gs_200, 1, 0) != EMPTY_VALUE) {
      ObjectSetText(str_concat_8, CharToStr(234), fontsize_4, "Wingdings", Arrow_Down_Color);
      return;
   }
   if (iCustom(NULL, gia_216[ai_0], gs_192, "", gs_200, 0, 0) != EMPTY_VALUE) {
      ObjectSetText(str_concat_8, CharToStr(233), fontsize_4, "Wingdings", Arrow_Up_Color);
      return;
   }
   if (iCustom(NULL, gia_216[ai_0], gs_192, "", gs_200, 2, 0) != EMPTY_VALUE) {
      ObjectSetText(str_concat_8, CharToStr(233), fontsize_4, "Wingdings", Arrow_Caution_Color);
      return;
   }
   if (iCustom(NULL, gia_216[ai_0], gs_192, "", gs_200, 3, 0) != EMPTY_VALUE) {
      ObjectSetText(str_concat_8, CharToStr(234), fontsize_4, "Wingdings", Arrow_Caution_Color);
      return;
   }
   if (iCustom(NULL, gia_216[ai_0], gs_208, 6, 0) < iCustom(NULL, gia_216[ai_0], gs_208, 7, 0)) {
      ObjectSetText(str_concat_8, CharToStr(110), fontsize_4, "Wingdings", APB_Up_Color);
      return;
   }
   ObjectSetText(str_concat_8, CharToStr(110), fontsize_4, "Wingdings", APB_Down_Color);
}

void f0_3() {
   int count_8;
   string name_20;
   int objs_total_0 = ObjectsTotal();
   int li_4 = 1000;
   for (int li_unused_16 = 2; li_4 > 0; li_4--) {
      count_8 = 0;
      for (int objs_total_12 = ObjectsTotal(); objs_total_12 > 0; objs_total_12--) {
         name_20 = ObjectName(objs_total_12);
         if (StringSubstr(name_20, 0, 9) == "SynProMTF") {
            count_8++;
            ObjectDelete(name_20);
         }
      }
      if (count_8 == 0) break;
   }
}