/*
   Generated by ex4-to-mq4 decompiler 4.0.495.4
   Website: hT T pS://P URe BE A m . b iz
   E-mail : g e TMQ4@ g maIl. c om
*/
#property copyright "Copyright 2011, AutoPipsProfit."
#property link      "autopipsprofit.com"

#property indicator_chart_window
#property indicator_buffers 1
#property indicator_color1 Black

string Gs_arial_76 = "Arial";
int G_fontsize_84 = 14;
int G_color_88 = White;
int G_corner_92 = 0;
int G_x_96 = 250;
int G_y_100 = 0;
int G_str_len_104;
string Gs_108 = ":...:...:...:...:";

int init() {
   G_str_len_104 = StringLen(Gs_108);
   return (0);
}
	 	      	  		 	 	   			  	 	 		 	 				   	   	  	  	  	  		 		 	 			   	    					 			 			 	   					 	    		   					 	  	 		 	 	 	   		 				   	 
int deinit() {
   if (ObjectFind("TS09") != -1) ObjectDelete("dpt04");
   return (0);
}
	 	  	  		  	  			    			 	 						 		 	 	 	  		 		  		 		 		  	   				        		 	 		  	 	 	 	 	 			    	 		 	 	 			      		   			    	  			 	 		
int start() {
   int Li_0 = 0;
   int Li_4 = 0;
   double Ld_8 = 0.0;
   string str_concat_16 = "";
   string Ls_24 = "";
   string Ls_32 = "";
   if (ObjectFind("TS09") == -1) {
      ObjectCreate("TS09", OBJ_LABEL, 0, 0, 0);
      ObjectSet("TS09", OBJPROP_XDISTANCE, G_x_96);
      ObjectSet("TS09", OBJPROP_YDISTANCE, G_y_100);
      ObjectSet("TS09", OBJPROP_CORNER, G_corner_92);
   }
   Li_4 = TimeCurrent() - Time[0];
   Li_0 = (G_str_len_104 - 1) * Li_4 / (60 * Period());
   Ld_8 = 100.0 * Li_4 / (60 * Period());
   if (Li_0 > G_str_len_104 - 1) Li_0 = G_str_len_104 - 1;
   if (Li_0 > 0) Ls_32 = StringSubstr(Gs_108, 0, Li_0);
   if (Li_0 < G_str_len_104 - 1) Ls_24 = StringSubstr(Gs_108, Li_0 + 1, G_str_len_104 - Li_0 - 1);
   str_concat_16 = StringConcatenate(Ls_32, "|", Ls_24, "  ", DoubleToStr(Ld_8, 0), "%");
   ObjectSetText("TS09", str_concat_16, G_fontsize_84, Gs_arial_76, G_color_88);
   return (0);
}
